### ISSUE TITLE
you've forgotten to put a semicolon in the first line xD

### ISSUE THREAD

**Issue by mahdoosh1** [metect/hello-js#1]

**Comment by metect** [comment]
I did this for fun. In fact, I do some of my tests in terminal(kde konsole) and by node. So far, I have not received an error because of the semicolon. Even if I delete the rest of the semicolons in the rest of the lines!

**Comment by mahdoosh1** [comment]
>  So far, I have not received an error because of the semicolon. Even if I delete the rest of the semicolons in the rest of the lines!

yes that's because they are in separate lines.
